version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        ports:
            - '8080:8080'
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:16-alpine
        restart: always
        env_file:
            - .env
        environment:
            PGDATA: /data/postgres
        volumes:
            - pgdata:/data/postgres
        healthcheck:
            test: [ 'CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}' ]
            interval: 5s
            timeout: 60s
            retries: 5
        logging:
            driver: none

volumes:
    pgdata:
